sonar.projectKey=aurify-backend_Aurify-Transaction
sonar.organization=aurify-backend
sonar.projectName=Aurify-Transaction
sonar.sources=.
sonar.exclusions=**/guidelines/**
sonar.go.coverage.reportPaths=coverage.out